(function(){
'use strict';
const cloud=()=>window.LDFCloud;const money=n=>Number(String(n??0).replace(/[^0-9.,-]/g,'').replace(',','.'))||0;
function cloudToLocalJob(j){return{id:j.id,title:j.title,city:j.city||'',cat:j.category||'Altele',budget:money(j.budget),start:'De stabilit',desc:j.description||'',access:0,max:j.max_unlocks||6,cost:j.unlock_fee||25,status:'activ',ownerId:j.client_id,workflowStatus:j.status==='completed'?'finalizat':j.status==='assigned'?'in_lucru':'disponibila',cloud:true,unlockedBy:[]};}
async function hydrateAccess(job){if(!job?.cloud||!cloud()?.getJobAccessSummary)return job;try{const s=await cloud().getJobAccessSummary(job.id);if(!s)return job;job.access=Math.min(Number(s.unlockCount||0),6);job.max=Math.min(Number(s.maxUnlocks||6),6);if(s.alreadyUnlocked&&typeof currentUser!=='undefined'&&currentUser){job.unlockedBy=Array.isArray(job.unlockedBy)?job.unlockedBy:[];if(!job.unlockedBy.map(String).includes(String(currentUser.id)))job.unlockedBy.push(currentUser.id);const contact=await cloud().getUnlockedContact(job.id).catch(()=>null);job.cloudPhone=contact?.phone||'';}}catch(err){console.warn('LDF access sync:',err)}return job;}
async function syncCloudState(){if(!cloud())return;try{const session=await cloud().getSession();const remoteJobs=await cloud().listOpenJobs();const mapped=remoteJobs.map(cloudToLocalJob);if(session?.user)await Promise.all(mapped.map(hydrateAccess));if(typeof jobs!=='undefined')jobs=[...mapped];if(session?.user){const[remoteSaved,profile,phone]=await Promise.all([cloud().listSavedJobs(),cloud().getMyProfile(),cloud().getMyPhone().catch(()=>'')]);if(typeof savedJobs!=='undefined'){const mine=remoteSaved.map(x=>({userId:session.user.id,jobId:x.job_id,savedAt:x.created_at,cloud:true}));const others=savedJobs.filter(x=>String(x.userId)!==String(session.user.id));savedJobs=[...mine,...others];}if(typeof currentUser!=='undefined'&&currentUser){currentUser.id=session.user.id;currentUser.name=profile.full_name||currentUser.name;currentUser.city=profile.city||currentUser.city||'';currentUser.county=profile.county||currentUser.county||'';currentUser.about=profile.bio||currentUser.about||'';currentUser.role=profile.role==='worker'?'meseriaș':'client';currentUser.email=session.user.email||currentUser.email||'';currentUser.phone=phone||'';}}if(typeof persist==='function')persist();if(typeof renderJobs==='function')renderJobs();if(typeof renderProfile==='function'&&session?.user)renderProfile();}catch(err){console.warn('LDF cloud sync:',err)}}
function installJobFormOverride(){const form=document.getElementById('jobForm');if(!form||form.dataset.cloudBound==='1')return;form.dataset.cloudBound='1';form.addEventListener('submit',function(e){if(!cloud())return;e.preventDefault();e.stopImmediatePropagation();(async()=>{try{if(typeof currentUser==='undefined'||!currentUser||currentUser.role!=='client'){toast?.('Trebuie să fii autentificat ca client.');nav?.('auth');return;}const phone=await cloud().getMyPhone().catch(()=>currentUser.phone||'');if(!phone){toast?.('Completează numărul de telefon în cont înainte de publicare.');nav?.('profile');return;}const fd=new FormData(form);const get=(...names)=>{for(const n of names){const el=form.elements[n]||document.getElementById(n);if(el?.value)return el.value;const v=fd.get(n);if(v)return v;}return''};const payload={title:get('title','jobTitle'),description:get('description','desc','jobDescription'),category:get('category','cat'),city:get('city','jobCity'),county:get('county'),budget:money(get('budget','jobBudget'))};if(!payload.title||!payload.description||payload.budget<=0){toast?.('Completează titlul, descrierea și bugetul lucrării.');return;}const result=await cloud().createPublishCheckout(payload);if(!result?.url)throw new Error('Nu am primit pagina de plată.');window.location.assign(result.url);}catch(err){console.error(err);toast?.(err?.message||'Nu am putut porni plata pentru publicare.');}})();},true);}
function installUnlockGuard(){const original=window.unlockContact;if(typeof original!=='function'||original.__ldfCloudWrapped)return;const wrapped=function(){const job=typeof selectedJob!=='undefined'?selectedJob:null;if(!job?.cloud||!cloud())return original();if(!currentUser||currentUser.role!=='meseriaș'){toast?.('Deblocarea este disponibilă pentru conturile de meseriaș.');nav?.('auth');return;}hydrateAccess(job).then(async()=>{if(job.unlockedBy?.map(String).includes(String(currentUser.id))){window.openJob(job.id);return;}if((job.access||0)>=6){toast?.('Limita de 6 meseriași a fost atinsă.');window.openJob(job.id);return;}try{const result=await window.createJobCheckout(job.id);if(!result?.url)throw new Error('Nu am primit pagina securizată de plată.');window.location.assign(result.url);}catch(err){console.error(err);toast?.(err?.message||'Nu am putut porni plata securizată.');}});};wrapped.__ldfCloudWrapped=true;window.unlockContact=wrapped;}
function install(){installJobFormOverride();installUnlockGuard();syncCloudState();}
window.addEventListener('ldfcloudready',install,{once:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,0),{once:true});else setTimeout(install,0);
})();