(function(){
'use strict';
const cloud=()=>window.LDFCloud;const money=n=>Number(String(n??0).replace(/[^0-9.,-]/g,'').replace(',','.'))||0;
function cloudToLocalJob(j){return{id:j.id,title:j.title,city:j.city||'',cat:j.category||'Altele',budget:money(j.budget),start:'De stabilit',desc:j.description||'',access:0,max:j.max_unlocks||6,cost:j.unlock_fee||25,status:'activ',ownerId:j.client_id,workflowStatus:j.status==='completed'?'finalizat':j.status==='assigned'?'in_lucru':'disponibila',cloud:true,unlockedBy:[]};}
async function hydrateAccess(job){if(!job?.cloud||!cloud()?.getJobAccessSummary)return job;try{const s=await cloud().getJobAccessSummary(job.id);if(!s)return job;job.access=Math.min(Number(s.unlockCount||0),6);job.max=Math.min(Number(s.maxUnlocks||6),6);if(s.alreadyUnlocked&&typeof currentUser!=='undefined'&&currentUser){job.unlockedBy=Array.isArray(job.unlockedBy)?job.unlockedBy:[];if(!job.unlockedBy.map(String).includes(String(currentUser.id)))job.unlockedBy.push(currentUser.id);const contact=await cloud().getUnlockedContact(job.id).catch(()=>null);job.cloudPhone=contact?.phone||'';}}catch(err){console.warn('LDF access sync:',err)}return job;}
async function syncCloudState(){if(!cloud())return;try{const session=await cloud().getSession();const remoteJobs=await cloud().listOpenJobs();const mapped=remoteJobs.map(cloudToLocalJob);if(session?.user)await Promise.all(mapped.map(hydrateAccess));if(typeof jobs!=='undefined')jobs=[...mapped];if(typeof renderJobs==='function')renderJobs();}catch(err){console.warn('LDF cloud sync:',err)}}
function installJobFormOverride(){const form=document.getElementById('jobForm');if(!form||form.dataset.cloudBound==='1')return;form.dataset.cloudBound='1';form.noValidate=true;form.querySelectorAll('[required]').forEach(el=>el.removeAttribute('required'));form.addEventListener('submit',function(e){if(!cloud())return;e.preventDefault();e.stopImmediatePropagation();(async()=>{try{const session=await cloud().getSession();if(!session?.user){toast?.('Trebuie să fii autentificat ca client.');nav?.('auth');return;}const profile=await cloud().getMyProfile();const isAdmin=profile?.role==='admin';if(profile?.role!=='client'&&!isAdmin){toast?.('Pentru publicare ai nevoie de cont de client.');return;}const phone=await cloud().getMyPhone().catch(()=>'');if(!phone){toast?.('Completează numărul de telefon în cont înainte de publicare.');nav?.('profile');return;}const q=id=>document.getElementById(id)?.value?.trim?.()||document.getElementById(id)?.value||'';const category=q('jobCategory');const city=q('jobCity');const description=q('jobDescription');const budget=money(q('jobBudget'));const payload={title:category||'Lucrare',description,category:category||'Alte lucrări',city,county:q('jobCounty')||'',budget,start:q('jobStart')||'De stabilit'};if(!city){toast?.('Completează orașul / localitatea.');return;}if(!description){toast?.('Descrie pe scurt lucrarea.');return;}if(budget<=0){toast?.('Completează bugetul estimat.');return;}if(isAdmin){const created=await cloud().createJob(payload);if(typeof jobs!=='undefined'&&created)jobs.unshift(created);if(typeof persist==='function')persist();form.reset();toast?.('Lucrarea a fost publicată gratuit cu succes.');nav?.('jobs');if(typeof renderJobs==='function')renderJobs();return;}const result=await cloud().createPublishCheckout(payload);if(!result?.url)throw new Error('Nu am primit pagina de plată.');window.location.assign(result.url);}catch(err){console.error(err);toast?.(err?.message||'Nu am putut publica lucrarea.');}})();},true);}
function installUnlockGuard(){const original=window.unlockContact;if(typeof original!=='function'||original.__ldfCloudWrapped)return;const wrapped=function(){const job=typeof selectedJob!=='undefined'?selectedJob:null;if(!job?.cloud||!cloud())return original();if(!currentUser||currentUser.role!=='meseriaș'){toast?.('Deblocarea este disponibilă pentru conturile de meseriaș.');nav?.('auth');return;}hydrateAccess(job).then(async()=>{try{const result=await window.createJobCheckout(job.id);if(!result?.url)throw new Error('Nu am primit pagina securizată de plată.');window.location.assign(result.url);}catch(err){console.error(err);toast?.(err?.message||'Nu am putut porni plata securizată.');}});};wrapped.__ldfCloudWrapped=true;window.unlockContact=wrapped;}
function install(){installJobFormOverride();installUnlockGuard();syncCloudState();}
window.addEventListener('ldfcloudready',install,{once:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,0),{once:true});else setTimeout(install,0);
})();