(function(){
  'use strict';
  function readyClient(){if(typeof supabaseClient!=='undefined'&&supabaseClient)return supabaseClient;if(typeof window.supabaseClient!=='undefined'&&window.supabaseClient)return window.supabaseClient;return null;}
  async function getSession(){const client=readyClient();if(!client)return null;const {data,error}=await client.auth.getSession();if(error)throw error;return data.session||null;}
  async function requireUser(){const session=await getSession();if(!session?.user)throw new Error('Trebuie să fii autentificat.');return session.user;}
  async function invokeAuthed(name,body){const client=readyClient();if(!client)throw new Error('Conexiunea la server nu este disponibilă.');const session=await getSession();if(!session?.access_token)throw new Error('Sesiunea a expirat. Autentifică-te din nou.');const {data,error}=await client.functions.invoke(name,{body,headers:{Authorization:`Bearer ${session.access_token}`}});if(error){let serverMessage='';try{const response=error.context;const parsed=response?.clone?await response.clone().json():null;serverMessage=parsed?.error||parsed?.message||'';}catch(_e){}throw new Error(serverMessage||error.message||'Eroare la server.');}if(data?.error)throw new Error(data.error);return data;}
  async function getMyProfile(){const client=readyClient(),user=await requireUser();const {data,error}=await client.from('profiles').select('id,role,full_name,city,county,bio,created_at,updated_at').eq('id',user.id).single();if(error)throw error;return data;}
  async function updateMyProfile(values){const client=readyClient(),user=await requireUser(),allowed={};['full_name','city','county','bio'].forEach(k=>{if(values&&Object.prototype.hasOwnProperty.call(values,k))allowed[k]=values[k];});allowed.updated_at=new Date().toISOString();const {data,error}=await client.from('profiles').update(allowed).eq('id',user.id).select().single();if(error)throw error;return data;}
  async function getMyPhone(){const client=readyClient(),user=await requireUser();const {data,error}=await client.from('profile_contacts').select('phone').eq('user_id',user.id).maybeSingle();if(error)throw error;return data?.phone||'';}
  async function setMyPhone(phone){const client=readyClient(),user=await requireUser(),value=String(phone||'').trim();if(value.length<7)throw new Error('Numărul de telefon este prea scurt.');const {data,error}=await client.from('profile_contacts').upsert({user_id:user.id,phone:value,updated_at:new Date().toISOString()},{onConflict:'user_id'}).select().single();if(error)throw error;return data;}
  async function listOpenJobs(){const client=readyClient();const {data,error}=await client.from('jobs').select('id,client_id,title,description,category,city,county,budget,status,created_at,publish_fee,unlock_fee,max_unlocks').eq('status','open').eq('payment_status','paid').order('created_at',{ascending:false});if(error)throw error;return data||[];}
  async function createPublishCheckout(job){const data=await invokeAuthed('create-publish-checkout',job);if(!data?.url)throw new Error('Nu am primit pagina securizată de plată.');return data;}
  async function createJob(job){return createPublishCheckout(job);}
  async function listSavedJobs(){const client=readyClient(),user=await requireUser();const {data,error}=await client.from('saved_jobs').select('job_id,created_at').eq('user_id',user.id).order('created_at',{ascending:false});if(error)throw error;return data||[];}
  async function saveJob(jobId){const client=readyClient(),user=await requireUser();const {data,error}=await client.from('saved_jobs').upsert({user_id:user.id,job_id:jobId},{onConflict:'user_id,job_id'}).select().single();if(error)throw error;return data;}
  async function unsaveJob(jobId){const client=readyClient(),user=await requireUser();const {error}=await client.from('saved_jobs').delete().eq('user_id',user.id).eq('job_id',jobId);if(error)throw error;return true;}
  async function getJobAccessSummary(jobId){const client=readyClient();await requireUser();const {data,error}=await client.rpc('get_job_access_summary',{p_job_id:jobId});if(error)throw error;const row=Array.isArray(data)?(data[0]||null):data;return row?{unlockCount:Number(row.unlock_count||0),maxUnlocks:Number(row.max_unlocks||6),alreadyUnlocked:!!row.already_unlocked}:null;}
  async function getUnlockedContact(jobId){const client=readyClient();await requireUser();const {data,error}=await client.rpc('get_unlocked_job_contact',{p_job_id:jobId});if(error)throw error;return Array.isArray(data)?(data[0]||null):data;}
  async function createJobCheckout(jobId){const summary=await getJobAccessSummary(jobId);if(summary?.alreadyUnlocked)throw new Error('Ai cumpărat deja această lucrare.');if(summary&&summary.unlockCount>=summary.maxUnlocks)throw new Error('Lucrarea a atins limita de meseriași.');const data=await invokeAuthed('create-job-checkout',{job_id:jobId});if(!data?.url)throw new Error('Nu am primit pagina securizată de plată.');return data;}
  async function ensureSupportThread(){const client=readyClient(),user=await requireUser();let {data,error}=await client.from('support_threads').select('id,user_id,subject,status,created_at,updated_at').eq('user_id',user.id).eq('status','open').order('created_at',{ascending:false}).limit(1);if(error)throw error;if(data&&data[0])return data[0];const created=await client.from('support_threads').insert({user_id:user.id,subject:'Asistență',status:'open'}).select('id,user_id,subject,status,created_at,updated_at').single();if(created.error)throw created.error;return created.data;}
  async function listSupportMessages(threadId){const client=readyClient();await requireUser();const {data,error}=await client.from('support_messages').select('id,thread_id,sender_id,body,created_at').eq('thread_id',threadId).order('created_at',{ascending:true});if(error)throw error;return data||[];}
  async function sendSupportMessage(threadId,body){const client=readyClient(),user=await requireUser(),text=String(body||'').trim();if(!text)throw new Error('Mesajul este gol.');let tid=threadId;if(!tid){const thread=await ensureSupportThread();tid=thread.id;}const {data,error}=await client.from('support_messages').insert({thread_id:tid,sender_id:user.id,body:text}).select('id,thread_id,sender_id,body,created_at').single();if(error)throw error;return data;}
  window.createJobCheckout=createJobCheckout;window.createPublishCheckout=createPublishCheckout;
  window.LDFCloud={getSession,getMyProfile,updateMyProfile,getMyPhone,setMyPhone,listOpenJobs,createJob,createPublishCheckout,listSavedJobs,saveJob,unsaveJob,getJobAccessSummary,getUnlockedContact,createJobCheckout,ensureSupportThread,listSupportMessages,sendSupportMessage};
  window.dispatchEvent(new CustomEvent('ldfcloudready'));
})();