(function(){
  'use strict';
  function readyClient(){if(typeof supabaseClient!=='undefined'&&supabaseClient)return supabaseClient;if(typeof window.supabaseClient!=='undefined'&&window.supabaseClient)return window.supabaseClient;return null;}
  async function getSession(){const client=readyClient();if(!client)return null;const {data,error}=await client.auth.getSession();if(error)throw error;return data.session||null;}
  async function requireUser(){const session=await getSession();if(!session?.user)throw new Error('Trebuie să fii autentificat.');return session.user;}
  async function getMyProfile(){const client=readyClient(),user=await requireUser();const {data,error}=await client.from('profiles').select('id,role,full_name,city,county,bio,created_at,updated_at').eq('id',user.id).single();if(error)throw error;return data;}
  async function updateMyProfile(values){const client=readyClient(),user=await requireUser(),allowed={};['full_name','city','county','bio'].forEach(k=>{if(values&&Object.prototype.hasOwnProperty.call(values,k))allowed[k]=values[k];});allowed.updated_at=new Date().toISOString();const {data,error}=await client.from('profiles').update(allowed).eq('id',user.id).select().single();if(error)throw error;return data;}
  async function getMyPhone(){const client=readyClient(),user=await requireUser();const {data,error}=await client.from('profile_contacts').select('phone').eq('user_id',user.id).maybeSingle();if(error)throw error;return data?.phone||'';}
  async function setMyPhone(phone){const client=readyClient(),user=await requireUser(),value=String(phone||'').trim();if(value.length<7)throw new Error('Numărul de telefon este prea scurt.');const {data,error}=await client.from('profile_contacts').upsert({user_id:user.id,phone:value,updated_at:new Date().toISOString()},{onConflict:'user_id'}).select().single();if(error)throw error;return data;}
  async function listOpenJobs(){const client=readyClient();const {data,error}=await client.from('jobs').select('id,client_id,title,description,category,city,county,budget,status,created_at,publish_fee,unlock_fee,max_unlocks').eq('status','open').eq('payment_status','paid').order('created_at',{ascending:false});if(error)throw error;return data||[];}
  async function createPublishCheckout(job){const client=readyClient();if(!client)throw new Error('Conexiunea la server nu este disponibilă.');await requireUser();const {data,error}=await client.functions.invoke('create-publish-checkout',{body:job});if(error)throw error;if(!data?.url)throw new Error(data?.error||'Nu am primit pagina securizată de plată.');return data;}
  async function createJob(job){return createPublishCheckout(job);}
  async function listSavedJobs(){const client=readyClient(),user=await requireUser();const {data,error}=await client.from('saved_jobs').select('job_id,created_at').eq('user_id',user.id).order('created_at',{ascending:false});if(error)throw error;return data||[];}
  async function saveJob(jobId){const client=readyClient(),user=await requireUser();const {data,error}=await client.from('saved_jobs').upsert({user_id:user.id,job_id:jobId},{onConflict:'user_id,job_id'}).select().single();if(error)throw error;return data;}
  async function unsaveJob(jobId){const client=readyClient(),user=await requireUser();const {error}=await client.from('saved_jobs').delete().eq('user_id',user.id).eq('job_id',jobId);if(error)throw error;return true;}
  async function getJobAccessSummary(jobId){const client=readyClient();await requireUser();const {data,error}=await client.rpc('get_job_access_summary',{p_job_id:jobId});if(error)throw error;const row=Array.isArray(data)?(data[0]||null):data;return row?{unlockCount:Number(row.unlock_count||0),maxUnlocks:Number(row.max_unlocks||6),alreadyUnlocked:!!row.already_unlocked}:null;}
  async function getUnlockedContact(jobId){const client=readyClient();await requireUser();const {data,error}=await client.rpc('get_unlocked_job_contact',{p_job_id:jobId});if(error)throw error;return Array.isArray(data)?(data[0]||null):data;}
  async function createJobCheckout(jobId){const client=readyClient();if(!client)throw new Error('Conexiunea la server nu este disponibilă.');const session=await getSession();if(!session?.access_token)throw new Error('Trebuie să fii autentificat.');const summary=await getJobAccessSummary(jobId);if(summary?.alreadyUnlocked)throw new Error('Ai cumpărat deja această lucrare.');if(summary&&summary.unlockCount>=summary.maxUnlocks)throw new Error('Lucrarea a atins limita de meseriași.');const {data,error}=await client.functions.invoke('create-job-checkout',{body:{job_id:jobId}});if(error)throw error;if(!data?.url)throw new Error('Nu am primit pagina securizată de plată.');return data;}
  async function sendSupportMessage(threadId,body){const client=readyClient(),user=await requireUser(),text=String(body||'').trim();if(!text)throw new Error('Mesajul este gol.');const {data,error}=await client.from('support_messages').insert({thread_id:threadId,sender_id:user.id,body:text}).select().single();if(error)throw error;return data;}
  window.createJobCheckout=createJobCheckout;window.createPublishCheckout=createPublishCheckout;
  window.LDFCloud={getSession,getMyProfile,updateMyProfile,getMyPhone,setMyPhone,listOpenJobs,createJob,createPublishCheckout,listSavedJobs,saveJob,unsaveJob,getJobAccessSummary,getUnlockedContact,createJobCheckout,sendSupportMessage};
  window.dispatchEvent(new CustomEvent('ldfcloudready'));
})();